backend:
  name: github
  repo: yoniliveonce/yonidegani.com
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "beyond_the_work"
    label: "Beyond the Work"
    folder: "content"
    create: true
    fields:
      - { label: "Photo", name: "image", widget: "image" }
      - { label: "Alt Text", name: "alt", widget: "string" }
